### ISSUE TITLE
Websocket getting 502 Bad Gateway error

### ISSUE THREAD

**Issue by Otokiru** [Xeio/WanderLost#169]
```
C:\nodejs\lostarkwei\node_modules\@microsoft\signalr\dist\cjs\HttpConnection.js:256
            return Promise.reject(new Errors_1.FailedToNegotiateWithServerError(errorMessage));
                                  ^

FailedToNegotiateWithServerError: Failed to complete negotiation with the server: Error: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
: Status code '502'
    at HttpConnection._getNegotiationResponse (C:\nodejs\lostarkwei\node_modules\@microsoft\signalr\dist\cjs\HttpConnection.js:256:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpConnection._createTransport (C:\nodejs\lostarkwei\node_modules\@microsoft\signalr\dist\cjs\HttpConnection.js:288:37)
    at async HttpConnection._startInternal (C:\nodejs\lostarkwei\node_modules\@microsoft\signalr\dist\cjs\HttpConnection.js:200:17)
    at async HttpConnection.start (C:\nodejs\lostarkwei\node_modules\@microsoft\signalr\dist\cjs\HttpConnection.js:75:9)
    at async HubConnection._startInternal (C:\nodejs\lostarkwei\node_modules\@microsoft\signalr\dist\cjs\HubConnection.js:132:9)
    at async HubConnection._startWithStateTransitions (C:\nodejs\lostarkwei\node_modules\@microsoft\signalr\dist\cjs\HubConnection.js:109:13) {
  errorType: 'FailedToNegotiateWithServerError'
}
```

Recently getting this error... any recent changes @Xeio?

**Comment by Xeio** [comment]
No issues that I'm aware of, just tried to connect with a small node client and it seems to log new merchants to the console fine too.

I did a small deployment yesterday for some dependency updates, but nothing that would have affected SignalR.

Could be my connection dropped for a bit or something, I think Cloudflare returns a 502 if it can't reach the origin server. You may want to have a longer retry-back-off policy in case the server goes down for a bit. I recall Spectrum had an outage for ~2 hours last month, but like I said nothing I'm aware of in the last day or so.
