### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by leowest77** [Xeio/WanderLost#194]
I keep getting this error and these images, can u advise me on what to do?

![image](https://github.com/Xeio/WanderLost/assets/132480836/a8f834c1-16a5-4edb-94f8-b4f6766e2ceb)
![image](https://github.com/Xeio/WanderLost/assets/132480836/718fa755-5249-46ae-b96f-8eee43e4abc3)

```
WebSocket connection to 'wss://hub.lostmerchants.com:15555/MerchantHub' failed: 
Ca @ dotnet.7.0.5.eztd5jwcvz.js:2
```

```
 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: net_webstatus_ConnectFailure
System.Net.WebSockets.WebSocketException (0x80004005): net_webstatus_ConnectFailure
 ---> WebSocket error
   at System.Net.WebSockets.BrowserWebSocket.CancelationHelper(Task , CancellationToken , WebSocketState )
   at System.Net.WebSockets.BrowserWebSocket.ConnectAsyncCore(Uri , List`1 , CancellationToken )
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri , HttpMessageInvoker , CancellationToken )
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.DefaultWebSocketFactory(WebSocketConnectionContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at WanderLost.Client.Services.MerchantHubClient.Connect()
   at WanderLost.Client.Pages.Merchants.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
u @ blazor.webassembly.js:1
```

**Comment by Xeio** [comment]
Do you get a mostly blank page when you hit https://hub.lostmerchants.com:15555/MerchantHub? It should just say something like "connection ID required".

**Comment by leowest77** [comment]
it says exactly that

**Comment by Xeio** [comment]
Hmm, strange, means something is going wrong with the connection for the web socket, but you can hit the endpoint directly. 🤔

**Comment by leowest77** [comment]
mmm any suggestions of what I could try?
