### ISSUE TITLE
Disconnected from server. Try to Reload.

### ISSUE THREAD

**Issue by Rootkit-** [Xeio/WanderLost#207]
![image](https://github.com/Xeio/WanderLost/assets/5389279/8243e71e-825a-429e-842b-e6cdef8267e9)

An unhandled error has occu

`WebSocket connection to 'wss://hub.lostmerchants.com:14124/MerchantHub?access_token=*' failed:`

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: net_webstatus_ConnectFailure
System.Net.WebSockets.WebSocketException (0x80004005): net_webstatus_ConnectFailure
 ---> WebSocket error
   at System.Net.WebSockets.BrowserWebSocket.CancelationHelper(Task , CancellationToken , WebSocketState )
   at System.Net.WebSockets.BrowserWebSocket.ConnectAsyncCore(Uri , List`1 , CancellationToken )
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri , HttpMessageInvoker , CancellationToken )
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.DefaultWebSocketFactory(WebSocketConnectionContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at WanderLost.Client.Services.MerchantHubClient.Connect()
   at WanderLost.Client.Pages.Merchants.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Comment by Rootkit-** [comment]
Chrome and Firefox.

**Comment by maviscass** [comment]
Me and my guildies are having the same issues.

**Comment by Xeio** [comment]
Seems the server got into a crash loop. Discord bot not quite bulletproof it seems and I need to add some error handling. 😅

**Comment by Xeio** [comment]
Should be recovered now, though I probably need to tweak some other things behind the scenes later on.
