### ISSUE TITLE
Unhandled Error, Firefox can't establish connection

### ISSUE THREAD

**Issue by SteveZinkeDev** [Xeio/WanderLost#215]
Since today, I get the following error:

Firefox can’t establish a connection to the server at wss://hub.lostmerchants.com:14124/MerchantHub?access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjVCNkYxQjE5Rjc1REE2NTVDMjMxNDc3NTc4Qzc0QkYzRjA0REU5NTEiLCJ4NXQiOiJXMjhiR2ZkZHBsWENNVWQxZU1kTDhfQk42VkUiLCJ0eXAiOiJhdCtqd3QifQ.eyJpc3MiOiJodHRwczovL2xvc3RtZXJjaGFudHMuY29tIiwibmJmIjoxNjkxODQ1MzM4LCJpYXQiOjE2OTE4NDUzMzgsImV4cCI6MTY5MTg0ODkzOCwiYXVkIjoiV2FuZGVyTG9zdC5TZXJ2ZXJBUEkiLCJzY29wZSI6WyJXYW5kZXJMb3N0LlNlcnZlckFQSSIsIm9wZW5pZCIsInByb2ZpbGUiXSwiYW1yIjpbImV4dGVybmFsIl0sImNsaWVudF9pZCI6IldhbmRlckxvc3QuQ2xpZW50Iiwic3ViIjoiN2MzNTQ0ZjAtYzQ5Yy00MTliLWI5YjgtYWEwNjBkNzJjMGY4IiwiYXV0aF90aW1lIjoxNjgzMjIxNzIxLCJpZHAiOiJEaXNjb3JkIiwic2lkIjoiRTcxQUIyMTJGQkQ0NDgzRDJCODUzQ0NGQTU0NDU1RjgiLCJqdGkiOiJEQ0ExRTk4NUY3QjNGQUVBQkNFMTA4QkI4NTZFRDRFNSJ9.YS52SPio08ulNW8489CCQrXo9pHewot9tVdj8w0QUmsMj3eOR478CMllzbFqFETxIYkxun2j9IbeOA4JksBYtA7FuJwEXtEMKN5gXAkz2GFzHm65QQ93wVaXfshBcXMLjxC40ALotM0PCGzJUYOvnGvQ7ZejpyAjUTt381DtxwjUv3737wrpFrOHd5cPYqOhXljX2YxY3dHhfwLxyZPz1xa6AKRhy2BpbyveddLC4aGqZL0mWCKlr_sCsdCgt2o9kVQ4listORwjeY7aawzedg8U4jsLhEFJRJXzgcG5ZvzJi0qKNqKCmu3OoWpUetwdPtEXlNowoOc1T7leuoklKMyyw0H1IgOnVL4_Tm1JuFAtCFDkqw0RF5j2lw8oIUNejxTxpQPr11wv9RtKPFAk097pKTton7lnEYQfhc8krUwL-LEcGtwC-Rr6cz4tfezliDzo6L4F7BTEyZ3rgCfKHhhdwJ9SntMPzlLAh9PABfZfacXPY0HCggovlYwdxAuHYhRO6iVZKhNJXPWYPqDoDu3JNadZKIjaooZUwrRpm6Tk7pkgjST2UtcbsYTGpOsJEFqDRdsZE9-J-K0yhSUw2ynzQC4q7NPYaTsESjmnnAEz9euY8-fJb0j1E2iFAjl9WQQj0Ca039N64s2zTtbO3lPzDIY_hQXYGNXWj-MzvBQ.

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: net_webstatus_ConnectFailure
System.Net.WebSockets.WebSocketException (0x80004005): net_webstatus_ConnectFailure
 ---> WebSocket error
   at System.Net.WebSockets.BrowserWebSocket.CancelationHelper(Task , CancellationToken , WebSocketState )
   at System.Net.WebSockets.BrowserWebSocket.ConnectAsyncCore(Uri , List`1 , CancellationToken )
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri , HttpMessageInvoker , CancellationToken )
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.DefaultWebSocketFactory(WebSocketConnectionContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at WanderLost.Client.Services.MerchantHubClient.Connect()
   at WanderLost.Client.Pages.Merchants.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
   
   
   I THINK (not entirely sure) that I updated Firefox this night and maybe this is the cause as it was fine before and still works in Chrome.

**Comment by Xeio** [comment]
Should be fixed now. Seems the proxy container didn't quite come back up from a restart in a fully expected state. Only Firefox cares about the particular SSL feature which is why it's the only one that blows up.
